/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package basarozkasli.view.swing;

/**
 *
 * @author basar
 */
import basarozkasli.dto.BookDTO;
import basarozkasli.domain.ReadStatus;
import basarozkasli.view.IBookDialog;
import basarozkasli.controller.IMainController;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.sql.Date;
public class BookDialog extends javax.swing.JDialog implements basarozkasli.view.IBookDialog {
        private IMainController controller;
    public BookDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ReadStatusComboBox.removeAllItems();
        for (ReadStatus status : ReadStatus.values()) {
            ReadStatusComboBox.addItem(status.name());
        }
        RatingComboBox.removeAllItems();
        for (int i = 1; i <= 5; i++) {
            RatingComboBox.addItem(String.valueOf(i));
        }
        
        YearSpinner.setValue(2025);
    }
    @Override
    public void showDialog() {
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }
    @Override
    public void setBookData(BookDTO book) {
        if (book != null) {
            TitleText.setText(book.getTitle());
            AuthorNameText.setText(book.getAuthorName());
            AuthorSurnameText.setText(book.getAuthorSurname());
            YearSpinner.setValue(book.getYear());
            NumberOfPagesText.setText(String.valueOf(book.getNumberOfPages()));
            AboutTextArea.setText(book.getAbout());
            ReadStatusComboBox.setSelectedItem(book.getReadStatus().name());
            RatingComboBox.setSelectedItem(String.valueOf(book.getRating()));
            CommentsTextArea.setText(book.getComments());
            RelaseDateText.setText(book.getReleaseDate() != null ? book.getReleaseDate().toString() : "");
        } else {
            TitleText.setText("");
            AuthorNameText.setText("");
            AuthorSurnameText.setText("");
            YearSpinner.setValue(2024);
            NumberOfPagesText.setText("");
            AboutTextArea.setText("");
            ReadStatusComboBox.setSelectedIndex(-1);
            RatingComboBox.setSelectedIndex(-1);
            CommentsTextArea.setText("");
            RelaseDateText.setText("");
        }
    }
     @Override
    public BookDTO getBookData() {
        BookDTO dto = new BookDTO();
        dto.setTitle(TitleText.getText());
        dto.setAuthorName(AuthorNameText.getText());
        dto.setAuthorSurname(AuthorSurnameText.getText());
        dto.setYear((Integer) YearSpinner.getValue());
        try {
            dto.setNumberOfPages(Integer.parseInt(NumberOfPagesText.getText()));
        } catch (NumberFormatException e) {
            dto.setNumberOfPages(0);
        }
        dto.setAbout(AboutTextArea.getText());
        dto.setReadStatus(ReadStatus.valueOf((String) ReadStatusComboBox.getSelectedItem()));
        try {
            dto.setRating(Integer.parseInt((String) RatingComboBox.getSelectedItem()));
        } catch (NumberFormatException e) {
            dto.setRating(0);
        }
        dto.setComments(CommentsTextArea.getText());
        if (!RelaseDateText.getText().isEmpty()) {
            try {
                dto.setReleaseDate(Date.valueOf(RelaseDateText.getText())); // yyyy-MM-dd beklenir
            } catch (Exception e) {
                dto.setReleaseDate(null);
            }
        } else {
            dto.setReleaseDate(null);
        }
        return dto;
    }
    @Override
    public void closeDialog() {
        this.dispose();
    }
    @Override
    public void setController(Object controller) {
        if (controller instanceof IMainController) {
            this.controller = (IMainController) controller;
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TitleLabel = new javax.swing.JLabel();
        TitleText = new javax.swing.JTextField();
        AuthorNameLabel = new javax.swing.JLabel();
        AuthorNameText = new javax.swing.JTextField();
        AuthorSurnamelabel = new javax.swing.JLabel();
        AuthorSurnameText = new javax.swing.JTextField();
        yearLabel = new javax.swing.JLabel();
        YearSpinner = new javax.swing.JSpinner();
        NumberOfPagesLabel = new javax.swing.JLabel();
        NumberOfPagesText = new javax.swing.JTextField();
        ReadStatusLabel = new javax.swing.JLabel();
        ReadStatusComboBox = new javax.swing.JComboBox<>();
        RatingComboBox = new javax.swing.JComboBox<>();
        RatingLabel = new javax.swing.JLabel();
        RelaseDateLabel = new javax.swing.JLabel();
        RelaseDateText = new javax.swing.JTextField();
        CommentsLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        CommentsTextArea = new javax.swing.JTextArea();
        AboutLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        AboutTextArea = new javax.swing.JTextArea();
        SaveButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        TitleLabel.setText("Title");

        TitleText.setText("Title");

        AuthorNameLabel.setText("Author Name");

        AuthorNameText.setText("Author Name");
        AuthorNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AuthorNameTextActionPerformed(evt);
            }
        });

        AuthorSurnamelabel.setText("Author Surname");

        AuthorSurnameText.setText("Author Surname");
        AuthorSurnameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AuthorSurnameTextActionPerformed(evt);
            }
        });

        yearLabel.setText("Year");

        NumberOfPagesLabel.setText("Number of Pages");

        ReadStatusLabel.setText("Read Status");

        ReadStatusComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ReadStatusComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReadStatusComboBoxActionPerformed(evt);
            }
        });

        RatingComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        RatingComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RatingComboBoxActionPerformed(evt);
            }
        });

        RatingLabel.setText("Rating");

        RelaseDateLabel.setText("Relase Date");

        RelaseDateText.setText("Relase Date");
        RelaseDateText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RelaseDateTextActionPerformed(evt);
            }
        });

        CommentsLabel.setText("Comments");

        CommentsTextArea.setColumns(20);
        CommentsTextArea.setRows(5);
        jScrollPane1.setViewportView(CommentsTextArea);

        AboutLabel.setText("About");

        AboutTextArea.setColumns(20);
        AboutTextArea.setRows(5);
        jScrollPane2.setViewportView(AboutTextArea);

        SaveButton.setText("Save");
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });

        CancelButton.setText("Cancel");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(AboutLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CommentsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(RelaseDateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                            .addComponent(RatingLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(RatingComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(RelaseDateText)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(SaveButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(CancelButton, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ReadStatusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(56, 56, 56)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(AuthorNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(AuthorSurnamelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(yearLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(NumberOfPagesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(AuthorNameText)
                                    .addComponent(AuthorSurnameText, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                    .addComponent(YearSpinner)
                                    .addComponent(NumberOfPagesText)
                                    .addComponent(ReadStatusComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TitleText, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(55, 55, 55))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TitleLabel)
                    .addComponent(TitleText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AuthorNameLabel)
                    .addComponent(AuthorNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AuthorSurnameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AuthorSurnamelabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(yearLabel)
                    .addComponent(YearSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NumberOfPagesText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NumberOfPagesLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ReadStatusLabel)
                    .addComponent(ReadStatusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RatingLabel)
                    .addComponent(RatingComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RelaseDateLabel)
                    .addComponent(RelaseDateText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CommentsLabel)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SaveButton, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AboutLabel)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(CancelButton)))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AuthorNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AuthorNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AuthorNameTextActionPerformed

    private void AuthorSurnameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AuthorSurnameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AuthorSurnameTextActionPerformed

    private void ReadStatusComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReadStatusComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReadStatusComboBoxActionPerformed

    private void RatingComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RatingComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RatingComboBoxActionPerformed

    private void RelaseDateTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RelaseDateTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RelaseDateTextActionPerformed

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
        // TODO add your handling code here:
        if (controller != null) {
            BookDTO dto = getBookData();   
            controller.handleAddBook(dto);
    }
    closeDialog();
    }//GEN-LAST:event_SaveButtonActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        // TODO add your handling code here:
        closeDialog();
    }//GEN-LAST:event_CancelButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                BookDialog dialog = new BookDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AboutLabel;
    private javax.swing.JTextArea AboutTextArea;
    private javax.swing.JLabel AuthorNameLabel;
    private javax.swing.JTextField AuthorNameText;
    private javax.swing.JTextField AuthorSurnameText;
    private javax.swing.JLabel AuthorSurnamelabel;
    private javax.swing.JButton CancelButton;
    private javax.swing.JLabel CommentsLabel;
    private javax.swing.JTextArea CommentsTextArea;
    private javax.swing.JLabel NumberOfPagesLabel;
    private javax.swing.JTextField NumberOfPagesText;
    private javax.swing.JComboBox<String> RatingComboBox;
    private javax.swing.JLabel RatingLabel;
    private javax.swing.JComboBox<String> ReadStatusComboBox;
    private javax.swing.JLabel ReadStatusLabel;
    private javax.swing.JLabel RelaseDateLabel;
    private javax.swing.JTextField RelaseDateText;
    private javax.swing.JButton SaveButton;
    private javax.swing.JLabel TitleLabel;
    private javax.swing.JTextField TitleText;
    private javax.swing.JSpinner YearSpinner;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel yearLabel;
    // End of variables declaration//GEN-END:variables
}
