/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package basarozkasli.view.swing;

/**
 *
 * @author basar
 */
import basarozkasli.view.ILoginView;
import basarozkasli.controller.LoginController;

import javax.swing.*;
public class LoginFrame extends javax.swing.JFrame implements ILoginView {
    private LoginController controller;

    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        System.out.println("DEBUG: LoginFrame başlatıldı");
        initComponents();
        try {
        basarozkasli.infrastructure.MySQLConnectionManager.getInstance().getConnection();
    } catch (Exception ex) {
        ex.printStackTrace();}
    }
     @Override
    public void setController(LoginController controller) {
        this.controller = controller;
    }
    @Override
    public void showError(String message) {
        JOptionPane.showMessageDialog(this, message, "Login Error", JOptionPane.ERROR_MESSAGE);
    }
    @Override
    public void showLoginForm() {
        setLocationRelativeTo(null);
        setVisible(true);
    }
    @Override
    public void closeView() {
        this.dispose();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userNameLabel = new javax.swing.JLabel();
        UserNameText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        PasswordPasswordField = new javax.swing.JPasswordField();
        LoginButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        userNameLabel.setText("User Name");

        UserNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserNameTextActionPerformed(evt);
            }
        });

        jLabel2.setText("Password");

        LoginButton.setText("Log in");
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(userNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(UserNameText)
                    .addComponent(PasswordPasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))
                .addContainerGap(140, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UserNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userNameLabel))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(PasswordPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addComponent(LoginButton)
                .addGap(65, 65, 65))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UserNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserNameTextActionPerformed

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        // TODO add your handling code here:
        System.out.println("DEBUG: Log in butonuna basıldı");
        String username = UserNameText.getText();
        String password = new String(PasswordPasswordField.getPassword());
    if (controller != null) {
        System.out.println("DEBUG: Controller null değil, handleLogin çağrılacak");
        controller.handleLogin(username, password);}
    else{
        System.out.println("DEBUG: Controller null!");
    }


    }//GEN-LAST:event_LoginButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (Exception ex) {
        ex.printStackTrace();
    }

    
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
           
            basarozkasli.repository.UserRepository userRepository = new basarozkasli.repository.impl.UserRepositoryImpl();
            basarozkasli.service.IAuthenticationService authService = new basarozkasli.service.impl.AuthenticationServiceImpl(userRepository);
            basarozkasli.view.IViewFactory viewFactory = new basarozkasli.view.swing.SwingViewFactory();

        
            LoginFrame loginFrame = new LoginFrame();

            
            basarozkasli.controller.LoginController loginController = new basarozkasli.controller.LoginController(authService, loginFrame, viewFactory);

         
            loginFrame.showLoginForm();
        }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LoginButton;
    private javax.swing.JPasswordField PasswordPasswordField;
    private javax.swing.JTextField UserNameText;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel userNameLabel;
    // End of variables declaration//GEN-END:variables
}
