
/**
 *
 * @author basar
 */
package basarozkasli.view.swing;
import basarozkasli.domain.Book;
import basarozkasli.domain.Author;
import basarozkasli.domain.User;
import basarozkasli.dto.BookDTO;
import basarozkasli.controller.IMainController;
import basarozkasli.view.IMainView;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.List;


public class Type1MainFrame extends javax.swing.JFrame implements IMainView {
    private IMainController controller;

    /**
     * Creates new form Type1MainFrame
     */
    public Type1MainFrame() {
        initComponents();
    }
    @Override
    public void showMainInterface(basarozkasli.domain.User user) {
        setTitle("Welcome, " + user.getUsername());
        setLocationRelativeTo(null);
        setVisible(true);
    }

    @Override
    public void setController(IMainController controller) {
        this.controller = controller;
    }

    @Override
    public void showBooks(List<Book> books) {
        String[] columns = {"Book ID", "Title", "Author ID", "Year", "Read Status", "Rating"};
        DefaultTableModel model = new DefaultTableModel(columns, 0);

        for (Book book : books) {
            Object[] row = {
                book.getBookId(),
                book.getTitle(),
                book.getAuthorId(),
                book.getYear(),
                book.getReadStatus(),
                book.getRating()
            };
            model.addRow(row);
        }
        BookTable.setModel(model);
    }
    @Override
    public void showAuthors(List<Author> authors) {
        String[] columns = {"Author ID", "Name", "Surname", "Website"};
        DefaultTableModel model = new DefaultTableModel(columns, 0);

        for (Author author : authors) {
            Object[] row = {
                author.getAuthorId(),
                author.getName(),
                author.getSurname(),
                author.getWebsite()
            };
            model.addRow(row);
        }
        BookTable.setModel(model);
    }
    @Override
    public void showBookDialog(Book book) {}
    
    @Override
    public void showError(String message) {
        JOptionPane.showMessageDialog(this, message, "Error", JOptionPane.ERROR_MESSAGE);
    }
    @Override
    public void showSuccess(String message) {
        JOptionPane.showMessageDialog(this, message, "Success", JOptionPane.INFORMATION_MESSAGE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        BookTable = new javax.swing.JTable();
        AddBookButton = new javax.swing.JButton();
        UpdateBookButton = new javax.swing.JButton();
        DeleteBookButton = new javax.swing.JButton();
        ShowFavouritesButton = new javax.swing.JButton();
        ShowUnreadButton = new javax.swing.JButton();
        ShowWishListButton = new javax.swing.JButton();
        ShowAuthorText = new javax.swing.JTextField();
        ShowAuthorButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BookTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(BookTable);

        AddBookButton.setText("Add Book");
        AddBookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBookButtonActionPerformed(evt);
            }
        });

        UpdateBookButton.setText("Update Book");
        UpdateBookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBookButtonActionPerformed(evt);
            }
        });

        DeleteBookButton.setText("Delete Book");
        DeleteBookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBookButtonActionPerformed(evt);
            }
        });

        ShowFavouritesButton.setText("Show Favourites");

        ShowUnreadButton.setText("Show Unread");
        ShowUnreadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowUnreadButtonActionPerformed(evt);
            }
        });

        ShowWishListButton.setText("Show Wishlist");
        ShowWishListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowWishListButtonActionPerformed(evt);
            }
        });

        ShowAuthorButton.setText("Show Author");
        ShowAuthorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowAuthorButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AddBookButton)
                .addGap(26, 26, 26)
                .addComponent(UpdateBookButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DeleteBookButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ShowFavouritesButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ShowUnreadButton)
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ShowAuthorButton)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ShowWishListButton)
                            .addComponent(ShowAuthorText, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(ShowAuthorText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ShowAuthorButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ShowWishListButton)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddBookButton)
                    .addComponent(UpdateBookButton)
                    .addComponent(DeleteBookButton)
                    .addComponent(ShowFavouritesButton)
                    .addComponent(ShowUnreadButton))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddBookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBookButtonActionPerformed
        // TODO add your handling code here:
    BookDialog dialog = new BookDialog(this, true); // 1. Dialog nesnesi
    dialog.showDialog();                            // 2. Dialogu aç
    BookDTO newBook = dialog.getBookData();         // 3. Kullanıcı verisi al
    if (controller != null && newBook != null) {
        controller.handleAddBook(newBook);}
    }//GEN-LAST:event_AddBookButtonActionPerformed

    private void UpdateBookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBookButtonActionPerformed
        // TODO add your handling code here:
    int selectedRow = BookTable.getSelectedRow();
    if (controller != null && selectedRow >= 0) {
        // 1. Seçili satırdan kitap ID’sini al
        int bookId = (int) BookTable.getValueAt(selectedRow, 0);

        // 2. Seçili kitap verisini controller’dan/servisten bulmak (örnek: getBookById)
        // Diyelim ki controller'ın getBookById fonksiyonu yoksa, Book nesnesini
        // tablo modelinden sadece temel bilgilerle doldurabilirsin:
        // (Yoksa bu satırı kendi mimarinde uygun şekilde değiştirmen gerekebilir)
        Book book = new Book();
        book.setBookId(bookId);
        book.setTitle((String) BookTable.getValueAt(selectedRow, 1));
        // Diğer alanları da aynı şekilde set edebilirsin...

        // 3. BookDialog’u aç ve mevcut bilgileri yükle
        BookDialog dialog = new BookDialog(this, true);
        // BookDTO'ya çevirip set edebilirsin:
        BookDTO dto = new BookDTO();
        dto.setTitle(book.getTitle());
        // Diğer BookDTO alanlarını da set edebilirsin...
        dialog.setBookData(dto);

        dialog.showDialog();

        BookDTO updatedBook = dialog.getBookData();

        if (updatedBook != null) {
            controller.handleUpdateBook(updatedBook);
        }
    }
    }//GEN-LAST:event_UpdateBookButtonActionPerformed

    private void DeleteBookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBookButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = BookTable.getSelectedRow();
        if (controller != null && selectedRow >= 0) {
            int bookId = (int) BookTable.getValueAt(selectedRow, 0);
            controller.handleDeleteBook(bookId);
            }
        }   
    private void ShowFavouritesButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                     
        // TODO add your handling code here:
        if (controller != null) controller.handleShowFavorites();                                                   
    }//GEN-LAST:event_DeleteBookButtonActionPerformed

    private void ShowUnreadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowUnreadButtonActionPerformed
        // TODO add your handling code here:    
     if (controller != null) controller.handleShowUnread();
    }//GEN-LAST:event_ShowUnreadButtonActionPerformed

    private void ShowWishListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowWishListButtonActionPerformed
        // TODO add your handling code here:
        if (controller != null) controller.handleShowWishlist();
    }//GEN-LAST:event_ShowWishListButtonActionPerformed

    private void ShowAuthorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowAuthorButtonActionPerformed
        // TODO add your handling code here:
    String searchText = ShowAuthorText.getText();
    if (controller != null) controller.handleSearchAuthor(searchText);
    }//GEN-LAST:event_ShowAuthorButtonActionPerformed
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Type1MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Type1MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Type1MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Type1MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Type1MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBookButton;
    private javax.swing.JTable BookTable;
    private javax.swing.JButton DeleteBookButton;
    private javax.swing.JButton ShowAuthorButton;
    private javax.swing.JTextField ShowAuthorText;
    private javax.swing.JButton ShowFavouritesButton;
    private javax.swing.JButton ShowUnreadButton;
    private javax.swing.JButton ShowWishListButton;
    private javax.swing.JButton UpdateBookButton;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
