/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package basarozkasli.view.swing;

/**
 *
 * @author basar
 */
import basarozkasli.domain.Book;
import basarozkasli.domain.Author;
import basarozkasli.controller.IMainController;
import basarozkasli.view.IMainView;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.List;
public class Type2MainFrame extends javax.swing.JFrame implements IMainView {
     private IMainController controller;
    /**
     * Creates new form Type2MainFrame
     */
    @Override
    public void showMainInterface(basarozkasli.domain.User user) {
        setTitle("Welcome, " + user.getUsername());
        setLocationRelativeTo(null);
        setVisible(true);
    }
    public Type2MainFrame() {
        initComponents();
    }
    @Override
    public void showBooks(List<Book> books) {
        String[] columns = {"Book ID", "Title", "Author ID", "Year", "Read Status", "Rating"};
        DefaultTableModel model = new DefaultTableModel(columns, 0);
        for (Book book : books) {
            Object[] row = {
                book.getBookId(),
                book.getTitle(),
                book.getAuthorId(),
                book.getYear(),
                book.getReadStatus(),
                book.getRating()
            };
            model.addRow(row);
        }
        BookTable.setModel(model);
    }
    @Override
    public void showAuthors(List<Author> authors) {
        String[] columns = {"Author ID", "Name", "Surname", "Website"};
        DefaultTableModel model = new DefaultTableModel(columns, 0);
        for (Author author : authors) {
            Object[] row = {
                author.getAuthorId(),
                author.getName(),
                author.getSurname(),
                author.getWebsite()
            };
            model.addRow(row);
        }
        BookTable.setModel(model);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
        public void showBookDialog(Book book) {
        // Bu ekranda kitap düzenleme/ekleme olmadığından boş bırakabilirsin
    }

    @Override
    public void showError(String message) {
        JOptionPane.showMessageDialog(this, message, "Error", JOptionPane.ERROR_MESSAGE);
    }

    @Override
    public void showSuccess(String message) {
        JOptionPane.showMessageDialog(this, message, "Success", JOptionPane.INFORMATION_MESSAGE);
    }

    @Override
    public void setController(IMainController controller) {
        this.controller = controller;
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        BookTable = new javax.swing.JTable();
        ShowFavouriteButton = new javax.swing.JButton();
        ShowUnreadButton = new javax.swing.JButton();
        ShowWishlistButton = new javax.swing.JButton();
        AuthorSearchText = new javax.swing.JTextField();
        AuthorSearchButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BookTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(BookTable);

        ShowFavouriteButton.setText("Show Favourites ");
        ShowFavouriteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowFavouriteButtonActionPerformed(evt);
            }
        });

        ShowUnreadButton.setText("Show Unread");
        ShowUnreadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowUnreadButtonActionPerformed(evt);
            }
        });

        ShowWishlistButton.setText("Show Wishlist");
        ShowWishlistButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowWishlistButtonActionPerformed(evt);
            }
        });

        AuthorSearchText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AuthorSearchTextActionPerformed(evt);
            }
        });

        AuthorSearchButton.setText("Author Search");
        AuthorSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AuthorSearchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AuthorSearchText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AuthorSearchButton))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(ShowFavouriteButton)
                .addGap(43, 43, 43)
                .addComponent(ShowUnreadButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ShowWishlistButton)
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(AuthorSearchText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(AuthorSearchButton)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ShowFavouriteButton)
                    .addComponent(ShowUnreadButton)
                    .addComponent(ShowWishlistButton))
                .addGap(0, 45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AuthorSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AuthorSearchButtonActionPerformed
        // TODO add your handling code here:
         if (controller != null) controller.handleShowFavorites();
    }//GEN-LAST:event_AuthorSearchButtonActionPerformed

    private void ShowFavouriteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowFavouriteButtonActionPerformed
        // TODO add your handling code here:
         if (controller != null) controller.handleShowUnread();
    }//GEN-LAST:event_ShowFavouriteButtonActionPerformed

    private void ShowUnreadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowUnreadButtonActionPerformed
        // TODO add your handling code here:
        if (controller != null) controller.handleShowWishlist();
    }//GEN-LAST:event_ShowUnreadButtonActionPerformed

    private void ShowWishlistButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowWishlistButtonActionPerformed
        // TODO add your handling code here:
      String searchText = AuthorSearchText.getText();
    if (controller != null) controller.handleSearchAuthor(searchText);
    }//GEN-LAST:event_ShowWishlistButtonActionPerformed

    private void AuthorSearchTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AuthorSearchTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AuthorSearchTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Type2MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Type2MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Type2MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Type2MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Type2MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AuthorSearchButton;
    private javax.swing.JTextField AuthorSearchText;
    private javax.swing.JTable BookTable;
    private javax.swing.JButton ShowFavouriteButton;
    private javax.swing.JButton ShowUnreadButton;
    private javax.swing.JButton ShowWishlistButton;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
